# Site Settings
title: Gareth Sheldon - CyberLair
description: Senior Technical and Cybersecurity Engineer | Firewalls, Forensics, Cloud Security
baseurl: "/CyberLair"  # Update this if your repo is not at the root
url: "https://gareth-cyberlord.github.io"  # Your GitHub Pages URL

# Theme Settings
theme: jekyll-theme-hacker  # Optional: Use a hacker-themed Jekyll theme

# Navigation
navbar:
  - name: Home
    url: /
  - name: About
    url: /about
  - name: Projects
    url: /projects
  - name: Labs
    url: /labs
  - name: Tools
    url: /tools
  - name: Contact
    url: /contact

# Social Links
social:
  - name: LinkedIn
    url: https://www.linkedin.com/in/gareth-sheldon
  - name: GitHub
    url: https://github.com/gareth-cyberlord
  - name: Email
    url: mailto:garethmsheldon@gmail.com

# Build Settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
